// <auto-generated />
using System;
using AdminMns.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminMns.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250520091223_20052025_DeuxiemeTentative")]
    partial class _20052025_DeuxiemeTentative
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AdminMns.Models.Absence", b =>
                {
                    b.Property<int>("IdAbsence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateDeclaration")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdRaisonAbsence")
                        .HasColumnType("int");

                    b.Property<int>("IdStagiaire")
                        .HasColumnType("int");

                    b.Property<string>("Justificatif")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdAbsence");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("AdminMns.Models.Administrateur", b =>
                {
                    b.Property<int>("IdAdministrateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateDeCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateDeNaissance")
                        .HasMaxLength(50)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdAdministrateur");

                    b.ToTable("Administrateurs");
                });

            modelBuilder.Entity("AdminMns.Models.Candidature", b =>
                {
                    b.Property<int>("IdCandidature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateSoumission")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TitreOuReference")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdCandidature");

                    b.ToTable("candidatures");

                    b.HasData(
                        new
                        {
                            IdCandidature = 1,
                            DateSoumission = new DateTime(2025, 3, 20, 9, 12, 22, 772, DateTimeKind.Utc).AddTicks(5913),
                            TitreOuReference = "Candidature Alpha - Session 2025"
                        },
                        new
                        {
                            IdCandidature = 2,
                            DateSoumission = new DateTime(2025, 4, 20, 9, 12, 22, 772, DateTimeKind.Utc).AddTicks(6306),
                            TitreOuReference = "Candidature Bravo - Session 2026"
                        });
                });

            modelBuilder.Entity("AdminMns.Models.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<int>("IdCandidature")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdClasse");

                    b.HasIndex("IdCandidature");

                    b.ToTable("classes");
                });

            modelBuilder.Entity("AdminMns.Models.ClasseStagiaire", b =>
                {
                    b.Property<int>("IdStagiaire")
                        .HasColumnType("int");

                    b.Property<int>("IdClasse")
                        .HasColumnType("int");

                    b.HasKey("IdStagiaire", "IdClasse");

                    b.ToTable("ClasseStagiaires");
                });

            modelBuilder.Entity("AdminMns.Models.CoursIntervenant", b =>
                {
                    b.Property<int>("IdPlanning")
                        .HasColumnType("int");

                    b.Property<int>("IdIntervenant")
                        .HasColumnType("int");

                    b.HasKey("IdPlanning", "IdIntervenant");

                    b.ToTable("CoursIntervenants");

                    b.HasData(
                        new
                        {
                            IdPlanning = 1,
                            IdIntervenant = 1
                        },
                        new
                        {
                            IdPlanning = 2,
                            IdIntervenant = 2
                        },
                        new
                        {
                            IdPlanning = 3,
                            IdIntervenant = 1
                        });
                });

            modelBuilder.Entity("AdminMns.Models.Document", b =>
                {
                    b.Property<int>("IdDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdCandidature")
                        .HasColumnType("int");

                    b.Property<string>("IdTypeDoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdDocument");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("AdminMns.Models.Entretien", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<int>("IdRendezVous")
                        .HasColumnType("int");

                    b.HasKey("IdUtilisateur", "IdRendezVous");

                    b.ToTable("Entretiens");
                });

            modelBuilder.Entity("AdminMns.Models.Intervenant", b =>
                {
                    b.Property<int>("IdIntervenant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateDeCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateDeNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdIntervenant");

                    b.ToTable("Intervenants");

                    b.HasData(
                        new
                        {
                            IdIntervenant = 1,
                            Adresse = "Canardville Docks",
                            DateDeCreation = new DateTime(2025, 5, 20, 11, 12, 22, 773, DateTimeKind.Local).AddTicks(4869),
                            Email = "donald.prof@disney.com",
                            IdUtilisateur = 3,
                            Nom = "Duck",
                            Prenom = "Donald",
                            Specialite = "Gestion de la Colère et Navigation",
                            Telephone = "555-QUACK",
                            Ville = "Canardville"
                        },
                        new
                        {
                            IdIntervenant = 2,
                            Adresse = "Chez Cendrillon",
                            DateDeCreation = new DateTime(2025, 5, 20, 11, 12, 22, 775, DateTimeKind.Local).AddTicks(8347),
                            Email = "fairy.godmother@disney.com",
                            IdUtilisateur = 2,
                            Nom = "Fairy",
                            Prenom = "Godmother",
                            Specialite = "Transformations Magiques",
                            Telephone = "555-MAGIC",
                            Ville = "Royaume Enchanté"
                        });
                });

            modelBuilder.Entity("AdminMns.Models.Photo", b =>
                {
                    b.Property<string>("IdPhoto")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdClasse")
                        .HasColumnType("int");

                    b.Property<int>("IdStagiaire")
                        .HasColumnType("int");

                    b.HasKey("IdPhoto");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("AdminMns.Models.Planning", b =>
                {
                    b.Property<int>("IdPlanning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Heure")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("Jour")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Salle")
                        .HasColumnType("int");

                    b.HasKey("IdPlanning");

                    b.ToTable("plannings", (string)null);

                    b.HasData(
                        new
                        {
                            IdPlanning = 1,
                            Heure = new TimeSpan(0, 10, 0, 0, 0),
                            Jour = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Salle = 101
                        },
                        new
                        {
                            IdPlanning = 2,
                            Heure = new TimeSpan(0, 14, 0, 0, 0),
                            Jour = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Salle = 202
                        },
                        new
                        {
                            IdPlanning = 3,
                            Heure = new TimeSpan(0, 9, 30, 0, 0),
                            Jour = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Salle = 101
                        });
                });

            modelBuilder.Entity("AdminMns.Models.PlanningClasse", b =>
                {
                    b.Property<int>("IdPlanning")
                        .HasColumnType("int");

                    b.Property<int>("IdClasse")
                        .HasColumnType("int");

                    b.HasKey("IdPlanning", "IdClasse");

                    b.ToTable("PlanningClasses");
                });

            modelBuilder.Entity("AdminMns.Models.RaisonAbsence", b =>
                {
                    b.Property<int>("IdRaisonAbsence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRaisonAbsence");

                    b.ToTable("RaisonsAbsence");
                });

            modelBuilder.Entity("AdminMns.Models.RaisonRetard", b =>
                {
                    b.Property<int>("IdRaisonRetard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRaisonRetard");

                    b.ToTable("RaisonsRetard");
                });

            modelBuilder.Entity("AdminMns.Models.RendezVous", b =>
                {
                    b.Property<int>("IdRendezVous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HeureRdv")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("JourRdv")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sujet")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRendezVous");

                    b.ToTable("RendezVous");
                });

            modelBuilder.Entity("AdminMns.Models.Retard", b =>
                {
                    b.Property<int>("IdRetard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateArrivee")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdRaisonRetard")
                        .HasColumnType("int");

                    b.Property<string>("Justificatif")
                        .HasColumnType("longtext");

                    b.HasKey("IdRetard");

                    b.ToTable("Retards");
                });

            modelBuilder.Entity("AdminMns.Models.RetardStagiaire", b =>
                {
                    b.Property<int>("IdStagiaire")
                        .HasColumnType("int");

                    b.Property<int>("IdRetard")
                        .HasColumnType("int");

                    b.HasKey("IdStagiaire", "IdRetard");

                    b.ToTable("RetardStagiaires");
                });

            modelBuilder.Entity("AdminMns.Models.Stagiaire", b =>
                {
                    b.Property<int>("IdStagiaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailStagiaire")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdStagiaire");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("stagiaire");

                    b.HasData(
                        new
                        {
                            IdStagiaire = 1,
                            Adresse = "1 Main Street",
                            DateNaissance = new DateTime(1928, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailStagiaire = "mickey.stagiaire@disney.com",
                            IdUtilisateur = 1,
                            Nom = "Mouse",
                            Prenom = "Mickey",
                            Telephone = "111-222-3333",
                            Ville = "Disneyland"
                        },
                        new
                        {
                            IdStagiaire = 2,
                            Adresse = "Château de Glace",
                            DateNaissance = new DateTime(1821, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailStagiaire = "elsa.stagiaire@disney.com",
                            IdUtilisateur = 4,
                            Nom = "Arendelle",
                            Prenom = "Elsa",
                            Telephone = "444-555-6666",
                            Ville = "Arendelle"
                        });
                });

            modelBuilder.Entity("AdminMns.Models.Status", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdStatus");

                    b.ToTable("status");

                    b.HasData(
                        new
                        {
                            IdStatus = 1,
                            Type = "Approuvé par le Roi Lion"
                        },
                        new
                        {
                            IdStatus = 2,
                            Type = "En attente de la Fée Clochette"
                        },
                        new
                        {
                            IdStatus = 3,
                            Type = "Rejeté par Maléfique"
                        },
                        new
                        {
                            IdStatus = 4,
                            Type = "Magie en cours"
                        });
                });

            modelBuilder.Entity("AdminMns.Models.TypeDoc", b =>
                {
                    b.Property<string>("IdTypeDoc")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTypeDoc");

                    b.ToTable("TypeDocs");
                });

            modelBuilder.Entity("Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("utilisateurs");

                    b.HasData(
                        new
                        {
                            IdUtilisateur = 1,
                            Email = "mickey.mouse@disney.com",
                            MotDePasse = "Password123!"
                        },
                        new
                        {
                            IdUtilisateur = 2,
                            Email = "minnie.mouse@disney.com",
                            MotDePasse = "MinniePass!"
                        },
                        new
                        {
                            IdUtilisateur = 3,
                            Email = "donald.duck@disney.com",
                            MotDePasse = "QuackQuack!"
                        },
                        new
                        {
                            IdUtilisateur = 4,
                            Email = "elsa.arendelle@disney.com",
                            MotDePasse = "LetItGo!"
                        },
                        new
                        {
                            IdUtilisateur = 5,
                            Email = "simba.lion@disney.com",
                            MotDePasse = "HakunaMatata!"
                        });
                });

            modelBuilder.Entity("AdminMns.Models.Classe", b =>
                {
                    b.HasOne("AdminMns.Models.Candidature", "Candidature")
                        .WithMany()
                        .HasForeignKey("IdCandidature")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("AdminMns.Models.Stagiaire", b =>
                {
                    b.HasOne("Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });
#pragma warning restore 612, 618
        }
    }
}
